jar ufm ../target/assistente-1.0.1.jar addToManifest.txt
jar ufm ../target/lib/commons-collections4-4.4.jar addToManifest.txt
jar ufm ../target/lib/commons-dbutils-1.7.jar addToManifest.txt
jar ufm ../target/lib/commons-lang3-3.9.jar addToManifest.txt
jar ufm ../target/lib/commons-text-1.8.jar addToManifest.txt
jar ufm ../target/lib/javafx-base-13-win.jar addToManifest.txt
jar ufm ../target/lib/javafx-base-13.jar addToManifest.txt
jar ufm ../target/lib/javafx-controls-13-win.jar addToManifest.txt
jar ufm ../target/lib/javafx-controls-13.jar addToManifest.txt
jar ufm ../target/lib/javafx-fxml-13-win.jar addToManifest.txt
jar ufm ../target/lib/javafx-fxml-13.jar addToManifest.txt
jar ufm ../target/lib/javafx-graphics-13-win.jar addToManifest.txt
jar ufm ../target/lib/javafx-graphics-13.jar addToManifest.txt
jar ufm ../target/lib/org.everit.osgi.bundles.net.sourceforge.jtds-1.3.1.jar addToManifest.txt
jar ufm ../target/lib/slf4j-api-1.7.28.jar addToManifest.txt
jar ufm ../target/lib/slf4j-simple-1.7.28.jar addToManifest.txt
jar ufm ../target/lib/snakeyaml-1.25.jar addToManifest.txt
jar ufm ../target/lib/sqlite-jdbc-3.28.0.jar addToManifest.txt
jar ufm ../target/lib/vavr-0.10.2.jar addToManifest.txt
jar ufm ../target/lib/vavr-match-0.10.2.jar addToManifest.txt
jar ufm ../target/lib/velocity-engine-core-2.1.jar addToManifest.txt